FROM public.ecr.aws/lambda/python:3.9

RUN pip install -U pip
RUN pip install pipenv 

COPY [ "Pipfile", "Pipfile.lock", "./" ]

RUN pipenv install --system --deploy

COPY [ "lambda_function_by_marcos.py", "./" ]
COPY [ "./credentials/credentials", "./credentials/config", "/root/.aws/" ]
# Alternative to copy credentials: run container with AWS env vars

CMD [ "lambda_function_by_marcos.lambda_handler" ]
